tasks:
  - init: |
      docker-compose build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)
  - command: docker-compose up -d
  
  - name: Open Bash
    command: |
      gp ports await 3000
      docker exec -ti simple-suggestion-box_web_1 bash


ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker