version: '3'
services:
  web:
    build: .
    command: bash -c "bundle exec puma -p 3000"
    volumes:
     - .:/simple-suggestion-box
    ports:
     - "3000:3000"
    depends_on:
     - mysql
  mysql:
    image: "mysql:5.7"
    environment:
     MYSQL_ROOT_PASSWORD: test
     MYSQL_USER: test
     MYSQL_PASSWORD: test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
     - mysql
    ports:
     - 80:80
    environment:
     - PMA_ARBITRARY=1
